### ISSUE TITLE
Using local ressources leads to red border on captcha frame

### ISSUE THREAD

**Issue by gcu-rohde** [vivirenremoto/doomcaptcha#10]
When trying to use local resources for script.js :
captcha_html += '<iframe id="doom_captcha" src="/doomcaptcha-main/captcha.html?version=' + captcha_version + '&sound=' + document.currentScript.getAttribute('sound') + '&countdown=' + document.currentScript.getAttribute('countdown') + '&enemies=' + captcha_enemies + '" style="width:300px;height:150px;border:2px black solid;"></iframe>';

Frame is loading, captcha is working but i have a red border on captcha when submitting form.
![Capture du 2021-05-29 10-57-28](https://user-images.githubusercontent.com/82823578/120064488-adcfa680-c06c-11eb-98e1-b68037e6a434.png)

**Comment by vivirenremoto** [comment]
hello,

check out the line 23 of script.js maybe here is problem 
https://github.com/vivirenremoto/doomcaptcha/blob/main/script.js#L23

i had to put this condition because some browser extensions uses the messages events and this prevents conflicts

hope this helps !

**Comment by gcu-rohde** [comment]
Hello, this is the issue; replacing the hostname value is the right way to make it work ! Well done.
