### ISSUE TITLE
Link to GitHub repo from demo and link to demo from repo?

### ISSUE THREAD

**Issue by karlhorky** [vivirenremoto/doomcaptcha#2]
Hi there, thanks for this project!

Would you be open to linking the following ways?

- from the demo page to the GitHub repo
- from the GitHub repo to the demo page (eg. from the About section)

This would help a bit in navigation and discovery of the code.

**Comment by vivirenremoto** [comment]
hi Karl, thats a good idea, thank you

**Comment by karlhorky** [comment]
Nice, looks good, thanks! 🙌 Closing.
