### ISSUE TITLE
Game tries to load with negative "enemies" parameter

### ISSUE THREAD

**Issue by KamilPiszczek** [vivirenremoto/doomcaptcha#3]
![image](https://user-images.githubusercontent.com/7335931/119541580-dc106600-bd8e-11eb-8028-a744f34376f7.png)

**Comment by vivirenremoto** [comment]
hello Kamil, can you tell me how you got this step by step to replicate the problem ? thanks

**Comment by vivirenremoto** [comment]
hello again,

i wrote a condition to check the number of enemies, is less than 1 the number of enemies will be four by default.

commit
https://github.com/vivirenremoto/doomcaptcha/commit/4d5e0172a48edd94562a9894b113cbe7c117097f

thanks
