### ISSUE TITLE
Headshots not counted

### ISSUE THREAD

**Issue by djsegal** [vivirenremoto/doomcaptcha#4]
The current hitbox for demons only includes their torso

**Comment by willsoares** [comment]
Same problem here
Firefox 88.0.1 (64-bits)

**Comment by vivirenremoto** [comment]
can you send me details please like device, browser, screenshot to replicate the same problem? thanks @djsegal @willsoares

**Comment by vivirenremoto** [comment]
hi there! finally i understand the problem, is something wrong with cursor position, so i tried to fix it with this commit 
https://github.com/vivirenremoto/doomcaptcha/commit/5b056b2df51d6e9b637af5dfa34a989852f8e336

**Comment by makc** [comment]
unfortunately it is still there, cursor goes white when aiming for the head (except for flaming skull guy)
