### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [vivirenremoto/doomcaptcha#5]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by vivirenremoto** [comment]
Hi Michael, thanks for the suggestion! I will take a look and decide later which one is better for this project :)

**Comment by TPS** [comment]
May I suggest https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository & GitHub's own https://choosealicense.com/ to assist your choice? 🙇🏾‍♂️

**Comment by vivirenremoto** [comment]
thank you @TechnologyClassroom  and @TPS , i'm not sure about if this is the best decision but i would like to see people contributions to the project so i decided to choose GPL :)

https://github.com/vivirenremoto/doomcaptcha/blob/main/LICENSE

**Comment by TPS** [comment]
@vivirenremoto Fantastic!  Great choice! 🙇🏾‍♂️

@vivirenremoto Close FTW?
